# Generated by Django 4.2.3 on 2023-07-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
